### ISSUE TITLE
Question about Authentication 

### ISSUE THREAD

**Issue by bskimball** [Capocaccia/fullstack#1]
Just a question. What are you planning to do about authentication?

I just built an app using a very similar set up (vue-cli, laravel, no typescript). I am using the jwt-auth library, and I created a vuex module for auth.

There's not a ton of documentation out there for authentication so I was wondering if I could have done it better. I also considered using Passport for authentication, as there is a section of the passport docs that refer to setting it up for an spa.

**Comment by Capocaccia** [comment]
I typically follow the standard Laravel Authentication for the most part but really this template doesnt care what you implement.  You could use a Auth0 or any other package to handle auth as well.  For instance, I might define a class method like the one below to handle simple authentication for a user:

    public function login() {

        $userData = array(
            //get the users email and password off of the request
            'email' => Input::get('email'),

            'password' => Input::get('password')

        );
        // find that user by email address on the user model
        $user = User::where('email', Input::get('email'))->first();
        //attempt to login with the userData provided via the request
        if(Auth::attempt($userData)) {
          //return success response if the Auth facade returns true
            return response()->json(['result' => 'success', 'user' => $user, 'redirect' => 'home']);

        } else {

            return response()->json(['result' => 'error', 'msg' => 'Incorrect password.']);

        }

    }

Laravel Auth Docs: https://laravel.com/docs/5.8/authentication
